# Generated by Django 4.2.30 on 2026-04-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento_observacoes_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='agendado', max_length=20),
        ),
    ]
